AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI on Lambda using Lambda Function URL

Globals:
  Function:
    Timeout: 10

Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: main.handler
      Runtime: python3.12
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE

Outputs:
  FunctionUrl:
    Description: "Public URL of the Lambda function"
    Value: !GetAtt FastApiFunction.FunctionUrl
