AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI on Lambda using Lambda Function URL

Globals:
  Function:
    Timeout: 10

Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.main.handler
      Runtime: python3.12
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE  # Public Function URL
Outputs:
  FunctionUrl:
    Description: "Lambda Function URL"
    Value: !GetAtt FastApiFunction.FunctionUrl
